import os
import json
import argparse
import time

import numpy as np
import torch
import matplotlib.pyplot as plt
from tqdm import tqdm
from PIL import Image
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from transformers import (
    AutoProcessor,
    LlavaForConditionalGeneration,
    BitsAndBytesConfig,
)

from utils.prompt_templates import build_visual_yesno_prompt
from utils.prompt_llava import _init_model, generate_output_for_model
from utils.attention_utils import get_entity_indices, get_phrase_token_positions

# --- Configuration ---
MODEL_ID = "llava-hf/llava-1.5-7b-hf"
BASE_DATA_PATH = f"/home/{os.environ['USER']}/DeepLearningProject/data/vlm_levels"

# bnb = BitsAndBytesConfig(
#     load_in_4bit=True,
#     bnb_4bit_quant_type="nf4",
#     bnb_4bit_compute_dtype=torch.float16,
# )


def _pick_model_input_device(model) -> torch.device:
    try:
        emb = model.get_input_embeddings()
        if emb is not None and hasattr(emb, "weight"):
            return emb.weight.device
    except Exception:
        pass

    try:
        return next(model.parameters()).device
    except Exception:
        return torch.device("cuda" if torch.cuda.is_available() else "cpu")


def _move_to_device(batch: dict, device: torch.device):
    out = {}
    for k, v in batch.items():
        out[k] = v.to(device) if hasattr(v, "to") else v
    return out


def extract_all_layer_hidden_states(model, processor, inputs, num_layers, first_token=False):
    
    input_length = inputs["input_ids"].shape[1]

    with torch.no_grad():
         outputs = model.generate(
            **inputs,
            max_new_tokens=1,
            # output_hidden_states is already set at model initialization, don't pass it here
            return_dict_in_generate=True,
            pad_token_id=processor.tokenizer.eos_token_id,
        )

    # outputs.hidden_states is a tuple of tuples: (step_0, step_1, ...)
    # Each step contains hidden states for all layers
    if outputs.hidden_states is None or len(outputs.hidden_states) == 0:
        raise ValueError("No hidden states returned from generation")

    # Check if a token was actually generated by comparing sequence lengths
    generated_sequence_length = outputs.sequences[0].shape[0] if hasattr(outputs, 'sequences') and len(outputs.sequences) > 0 else input_length
    token_was_generated = generated_sequence_length > input_length

    # Step 0 = input step, Step 1 = first generated token step
    if first_token:
        # Check if a token was actually generated
        if not token_was_generated:
            raise ValueError(f"No new token generated. Input length: {input_length}, Generated sequence length: {generated_sequence_length}")
        
        # Check if we have a second step (first generated token)
        if len(outputs.hidden_states) < 2:
            # Workaround: Use forward pass to get hidden states for the generated token
            # Get the generated token ID
            generated_token_id = outputs.sequences[0][input_length:input_length+1]
            
            # Append generated token to input and do forward pass
            full_input_ids = torch.cat([inputs["input_ids"], generated_token_id.unsqueeze(0)], dim=1)
            
            # Update attention mask if present
            if "attention_mask" in inputs:
                full_attention_mask = torch.cat([
                    inputs["attention_mask"], 
                    torch.ones((1, 1), device=inputs["attention_mask"].device, dtype=inputs["attention_mask"].dtype)
                ], dim=1)
            else:
                full_attention_mask = None
            
            # Prepare model_kwargs (for vision model, need pixel_values, etc.)
            model_kwargs = {k: v for k, v in inputs.items() if k not in ("input_ids", "attention_mask")}
            
            # Forward pass to get hidden states
            with torch.no_grad():
                forward_outputs = model(
                    input_ids=full_input_ids,
                    attention_mask=full_attention_mask,
                    output_hidden_states=True,
                    return_dict=True,
                    **model_kwargs
                )
            
            # Use hidden states from forward pass
            input_step_hidden_states = forward_outputs.hidden_states
        else:
            input_step_hidden_states = outputs.hidden_states[1]
    else:
        input_step_hidden_states = outputs.hidden_states[0]

    # Extract hidden state at the decision point for all layers
    all_layer_hidden_states = {}
    for layer_idx in range(num_layers):
        # layer_hidden shape: (batch, seq_len, hidden_dim)
        layer_hidden = input_step_hidden_states[layer_idx]
        if first_token:
            # For first generated token, the sequence length should be input_length + 1
            seq_len = layer_hidden.shape[1]
            if seq_len <= input_length:
                raise ValueError(f"Expected sequence length > {input_length} for first token, got {seq_len}")
            decision_point_hidden = layer_hidden[0, input_length, :]  # First generated token position
        else:
            decision_point_hidden = layer_hidden[0, input_length - 1, :]  # Last input token position
        all_layer_hidden_states[layer_idx] = decision_point_hidden.detach().cpu().numpy()

    return all_layer_hidden_states


def collect_probing_data(model, processor, level, max_images=None, first_token=False):

    level_dir = os.path.join(BASE_DATA_PATH, f"level_{level}")
    ann_dir = os.path.join(level_dir, "ann")
    # ann_dir = os.path.join(base_dir, "ann")
    img_dir = os.path.join(level_dir, "images")
    # img_dir = os.path.join(base_dir, "images")

    if not os.path.exists(ann_dir):
        raise FileNotFoundError(f"Level {level} directory not found: {ann_dir}")

    json_files = sorted([f for f in os.listdir(ann_dir) if f.endswith(".json")])
    if max_images:
        json_files = json_files[:max_images]

    # Determine number of layers from model
    num_layers = len(model.language_model.layers)
    hidden_states_by_layer = {i: [] for i in range(num_layers)}
    labels = []
    metadata = []

    device = _pick_model_input_device(model)

    print(f"Collecting data from {len(json_files)} images...")

    for filename in tqdm(json_files, desc="Processing images"):
        file_id = filename.replace(".json", "")
        ann_path = os.path.join(ann_dir, filename)

        with open(ann_path, "r") as f:
            data = json.load(f)

        image_path = os.path.join(img_dir, f"{file_id}.png")
        if not os.path.exists(image_path):
            continue

        image = Image.open(image_path).convert("RGB")

        qa_list = data.get("qa", [])

        for qa in qa_list:
            question = (qa.get("question") or "").strip()
            gt = (qa.get("answer") or "").strip().lower()

            if not question or gt not in {"yes", "no"}:
                continue

            # Prepare inputs
            conversation = build_visual_yesno_prompt(question)
            prompt_text = processor.apply_chat_template(
                conversation,
                add_generation_prompt=True,
                tokenize=False,
            )
            inputs = processor(text=prompt_text, images=image, return_tensors="pt")
            inputs = _move_to_device(inputs, device)

            # Extract hidden states from all layers in a single generation pass
            try:
                all_layer_states = extract_all_layer_hidden_states(
                    model, processor, inputs, num_layers, first_token
                )

                # Store hidden states for each layer
                for layer_idx, hidden_state in all_layer_states.items():
                    hidden_states_by_layer[layer_idx].append(hidden_state)

                # Store label (0=no, 1=yes)
                labels.append(1 if gt == "yes" else 0)
                metadata.append(
                    {
                        "image": file_id,
                        "question": question,
                        "ground_truth": gt,
                    }
                )
            except Exception as e:
                print(
                    f"Error processing {file_id}, question: {question[:50]}... - {e}"
                )

    print(f"Collected {len(labels)} examples")
    return hidden_states_by_layer, labels, metadata


def probe_layer(hidden_states, labels, cv_folds=5):
    """
    Train a linear probe on hidden states and return cross-validation accuracy.

    Args:
        hidden_states: list of numpy arrays, each of shape (hidden_dim,)
        labels: list of binary labels (0 or 1)
        cv_folds: number of cross-validation folds

    Returns:
        mean_accuracy: mean CV accuracy
        std_accuracy: std of CV accuracy
    """
    if len(hidden_states) != len(labels):
        raise ValueError(
            f"Mismatch: {len(hidden_states)} hidden states, {len(labels)} labels"
        )

    if len(set(labels)) < 2:
        # Need at least 2 classes
        return 0.0, 0.0

    # Convert to numpy arrays
    X = np.array(hidden_states)  # Shape: (n_samples, hidden_dim)
    y = np.array(labels)  # Shape: (n_samples,)

    # Train linear probe with cross-validation
    probe = LogisticRegression(max_iter=1000, random_state=42)
    cv_scores = cross_val_score(probe, X, y, cv=cv_folds, scoring="accuracy")

    return cv_scores.mean(), cv_scores.std()

def extract_all_head_attentions(model, processor, inputs, specific_layers=[13, 16, 19, 24], first_token=False):
    """
    Extract attention patterns from specific heads in specific layers.
    
    Args:
        model: The LLaVA model
        processor: The processor
        inputs: Model inputs
        specific_layers: List of layer indices to extract from
        first_token: Whether to use first generated token or last input token (currently only last input token supported)
    
    Returns:
        Dictionary: {layer_idx: {head_idx: attention_pattern}}
        where attention_pattern is attention from last token to image patches [num_image_tokens]
    """
    input_length = inputs["input_ids"].shape[1]
    
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=1,
            output_attentions=True,
            return_dict_in_generate=True,
            pad_token_id=processor.tokenizer.eos_token_id,
        )
    
    if not outputs.attentions or len(outputs.attentions) == 0:
        raise ValueError("No attentions returned from generation")
    
    # Use step 0 (input step) - attention from input tokens
    input_step_attentions = outputs.attentions[0]  # tuple of [num_layers] tensors
    
    # Get image token positions
    image_token_id = model.config.image_token_index
    full_input_ids = inputs["input_ids"][0]  # [seq_len]
    image_token_positions = (full_input_ids == image_token_id).nonzero(as_tuple=True)[0].tolist()
    
    if not image_token_positions:
        raise ValueError("No image tokens found in sequence")
    
    last_token_idx = input_length - 1
    
    # Extract attention patterns for each head in specified layers
    all_head_attentions = {}
    for layer_idx in specific_layers:
        if layer_idx >= len(input_step_attentions):
            continue
        
        layer_attn = input_step_attentions[layer_idx]  # [1, heads, seq, seq]
        layer_attn = layer_attn[0]  # Remove batch dim: [heads, seq, seq]
        num_heads = layer_attn.shape[0]
        all_head_attentions[layer_idx] = {}
        
        for head_idx in range(num_heads):
            # Get attention from last input token to all tokens
            head_attn = layer_attn[head_idx, last_token_idx, :]  # [seq]
            
            # Extract attention to image patches only
            image_attn = head_attn[image_token_positions]  # [num_image_tokens]
            
            # Normalize to get probability distribution
            image_attn_sum = image_attn.sum()
            if image_attn_sum > 0:
                image_attn_probs = image_attn / image_attn_sum
            else:
                image_attn_probs = image_attn
            
            all_head_attentions[layer_idx][head_idx] = image_attn_probs.detach().cpu().numpy()
    
    return all_head_attentions

def collect_head_probing_data(model, processor, level, max_images=None, 
                              specific_layers=[13, 16, 19, 24], first_token=False):
    """
    Collect head-specific attention patterns for probing.
    Reuses the same structure as collect_probing_data but extracts attentions instead.
    """
    level_dir = os.path.join(BASE_DATA_PATH, f"level_{level}")
    ann_dir = os.path.join(level_dir, "ann")
    img_dir = os.path.join(level_dir, "images")
    
    if not os.path.exists(ann_dir):
        raise FileNotFoundError(f"Level {level} directory not found: {ann_dir}")
    
    json_files = sorted([f for f in os.listdir(ann_dir) if f.endswith(".json")])
    if max_images:
        json_files = json_files[:max_images]
    
    # Structure: {layer: {head: [features...]}}
    head_features_by_layer_head = {}
    for layer in specific_layers:
        head_features_by_layer_head[layer] = {head: [] for head in range(32)}
    
    labels = []
    metadata = []
    
    device = _pick_model_input_device(model)
    
    print(f"Collecting head probing data from {len(json_files)} images...")
    
    for filename in tqdm(json_files, desc="Processing images"):
        file_id = filename.replace(".json", "")
        ann_path = os.path.join(ann_dir, filename)
        
        with open(ann_path, "r") as f:
            data = json.load(f)
        
        image_path = os.path.join(img_dir, f"{file_id}.png")
        if not os.path.exists(image_path):
            continue
        
        image = Image.open(image_path).convert("RGB")
        qa_list = data.get("qa", [])
        
        for qa in qa_list:
            question = (qa.get("question") or "").strip()
            gt = (qa.get("answer") or "").strip().lower()
            
            if not question or gt not in {"yes", "no"}:
                continue
            
            # Prepare inputs (same as collect_probing_data)
            conversation = build_visual_yesno_prompt(question)
            prompt_text = processor.apply_chat_template(
                conversation,
                add_generation_prompt=True,
                tokenize=False,
            )
            inputs = processor(text=prompt_text, images=image, return_tensors="pt")
            inputs = _move_to_device(inputs, device)
            
            # Extract head attentions (instead of hidden states)
            try:
                all_head_attentions = extract_all_head_attentions(
                    model, processor, inputs, specific_layers, first_token
                )
                
                # Store attention patterns for each head in each layer
                for layer_idx, heads in all_head_attentions.items():
                    for head_idx, attention_pattern in heads.items():
                        head_features_by_layer_head[layer_idx][head_idx].append(attention_pattern)
                
                # Store label (0=no, 1=yes) - same as collect_probing_data
                labels.append(1 if gt == "yes" else 0)
                metadata.append({
                    "image": file_id,
                    "question": question,
                    "ground_truth": gt,
                })
            except Exception as e:
                print(f"Error processing {file_id}, question: {question[:50]}... - {e}")
    
    print(f"Collected {len(labels)} examples")
    return head_features_by_layer_head, labels, metadata

def probe_head(head_features, labels, cv_folds=5):
    """
    Train a linear probe on head-specific features and return cross-validation accuracy.
    Same pattern as probe_layer.
    
    Args:
        head_features: list of numpy arrays, each representing features from a specific head
                      (e.g., attention pattern from that head)
        labels: list of binary labels (0 or 1)
        cv_folds: number of cross-validation folds
    
    Returns:
        mean_accuracy: mean CV accuracy
        std_accuracy: std of CV accuracy
    """
    if len(head_features) != len(labels):
        raise ValueError(
            f"Mismatch: {len(head_features)} head features, {len(labels)} labels"
        )
    
    if len(set(labels)) < 2:
        return 0.0, 0.0
    
    X = np.array(head_features)  # Shape: (n_samples, feature_dim)
    y = np.array(labels)
    
    probe = LogisticRegression(max_iter=1000, random_state=42)
    cv_scores = cross_val_score(probe, X, y, cv=cv_folds, scoring="accuracy")
    
    return cv_scores.mean(), cv_scores.std()

def collect_head_com_data(model, processor, level, max_images=None, 
                          specific_layers=None, source_token_type="object"):
    """
    Collect center of mass data for attention heads across specified layers.
    
    Args:
        model: The LLaVA model
        processor: The processor
        level: Data level to process
        max_images: Maximum number of images to process
        specific_layers: List of layer indices to analyze (None = all layers)
        source_token_type: Which token to use as source for attention. Options: "subject", "relation", "object"
    
    Returns:
        List of dictionaries containing CoM results for each image/QA pair
    """
    level_dir = os.path.join(BASE_DATA_PATH, f"level_{level}")
    ann_dir = os.path.join(level_dir, "ann")
    img_dir = os.path.join(level_dir, "images")
    
    if not os.path.exists(ann_dir):
        raise FileNotFoundError(f"Level {level} directory not found: {ann_dir}")
    
    json_files = sorted([f for f in os.listdir(ann_dir) if f.endswith(".json")])
    if max_images:
        json_files = json_files[:max_images]
    
    device = _pick_model_input_device(model)
    all_com_results = []
    
    print(f"Collecting head CoM data from {len(json_files)} images...")
    
    for filename in tqdm(json_files, desc="Processing images"):
        file_id = filename.replace(".json", "")
        ann_path = os.path.join(ann_dir, filename)
        
        with open(ann_path, "r") as f:
            annotation = json.load(f)
        
        image_path = os.path.join(img_dir, f"{file_id}.png")
        if not os.path.exists(image_path):
            continue
        
        image = Image.open(image_path).convert("RGB")
        qa_list = annotation.get("qa", [])
        
        for qa_pair in qa_list:
            question = (qa_pair.get("question") or "").strip()
            if not question:
                continue
            
            # Prepare inputs
            conversation = build_visual_yesno_prompt(question)
            prompt_text = processor.apply_chat_template(
                conversation,
                add_generation_prompt=True,
                tokenize=False,
            )
            inputs = processor(text=prompt_text, images=image, return_tensors="pt")
            inputs = _move_to_device(inputs, device)
            
            # Calculate CoM for this QA pair
            try:
                com_results = calc_com(
                    model, processor, inputs, image, annotation, qa_pair,
                    specific_layers=specific_layers,
                    source_token_type=source_token_type
                )
                
                all_com_results.append({
                    "image_id": file_id,
                    "qa_id": qa_pair.get("id"),
                    "question": question,
                    "ground_truth": qa_pair.get("answer"),
                    "com_results": com_results,
                    "source_token_type": source_token_type
                })
            except Exception as e:
                print(
                    f"Error processing {file_id}, question: {question[:50]}... - {e}"
                )
                continue
    
    return all_com_results

def calc_com(model, processor, inputs, image, annotation, qa_pair, 
             specific_layers=None, source_token_type="object"):
    """
    Calculate the center of mass distance between the head attention map and the ground truth centers
    for both subject and object.
    
    Uses attention from a specified source token (subject, relation, or object) instead of the last input token.
    
    Args:
        model: The LLaVA model
        processor: The processor
        inputs: Model inputs (from processor)
        image: PIL Image
        annotation: Annotation dict with objects and meta
        qa_pair: QA pair dict with subject_id/object_id
        specific_layers: List of layer indices to analyze (None = all layers)
        source_token_type: Which token to use as source for attention. Options: "subject", "relation", "object"
    
    Returns:
        Dictionary with per-layer, per-head center of mass distances to subject and object centers
    """
    input_length = inputs["input_ids"].shape[1]
    
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=1,
            # output_hidden_states=True,
            output_attentions=True,
            return_dict_in_generate=True,
            pad_token_id=processor.tokenizer.eos_token_id,
        )
    
    if not outputs.attentions or len(outputs.attentions) == 0:
        raise ValueError("No attentions returned from generation")
    
    # Use step 0 (input step) - attention from input tokens
    input_step_attentions = outputs.attentions[0]  # tuple of [num_layers] tensors
    
    # If specific_layers is None, use all layers
    if specific_layers is None:
        num_layers = len(input_step_attentions)
        specific_layers = list(range(num_layers))
    
    # Get image token positions
    image_token_id = model.config.image_token_index
    full_input_ids = inputs["input_ids"][0]  # [seq_len]
    image_token_positions = (full_input_ids == image_token_id).nonzero(as_tuple=True)[0].tolist()
    
    if not image_token_positions:
        raise ValueError("No image tokens found in sequence")
    
    # Get entity token positions
    entity_indices = get_entity_indices(
        processor.tokenizer,
        full_input_ids,
        qa_pair,
        annotation
    )

    # sub_idxs = entity_indices.get("subject", [])
    # obj_idxs = entity_indices.get("object", [])    
    # print("Decoded subject span:",
    #   processor.tokenizer.decode(full_input_ids[sub_idxs[0]:sub_idxs[-1]+1]))
    # print("Decoded object span:",
    #     processor.tokenizer.decode(full_input_ids[obj_idxs[0]:obj_idxs[-1]+1]))
    
    # Select source token based on source_token_type
    source_token_idx = None
    source_token_name = None
    
    if source_token_type == "subject":
        subject_token_indices = entity_indices.get("subject", [])
        if not subject_token_indices:
            raise ValueError(f"Subject tokens not found in sequence for subject_id={qa_pair.get('subject_id')}")
        source_token_idx = subject_token_indices[-1]  # Use last token of subject phrase
        source_token_name = "subject"
    
    elif source_token_type == "relation":
        rel_phrase = qa_pair.get("rel_phrase", "")
        if not rel_phrase:
            raise ValueError(f"rel_phrase not found in qa_pair")
        relation_indices = get_phrase_token_positions(
            processor.tokenizer,
            full_input_ids,
            rel_phrase
        ).get("relation", [])
        if not relation_indices:
            raise ValueError(f"Relation tokens not found for rel_phrase='{rel_phrase}'")
        source_token_idx = relation_indices[-1]  # Use last token of relation phrase
        source_token_name = "relation"
    
    elif source_token_type == "object":
        object_token_indices = entity_indices.get("object", [])
        if not object_token_indices:
            raise ValueError(f"Object tokens not found in sequence for object_id={qa_pair.get('object_id')}")
        source_token_idx = object_token_indices[-1]  # Use last token of object phrase
        source_token_name = "object"
    
    else:
        raise ValueError(f"Invalid source_token_type: {source_token_type}. Must be 'subject', 'relation', or 'object'")
    
    # Get metadata
    grid_dim = annotation.get("meta", {}).get("grid_dim", 24)
    patch_size = annotation.get("meta", {}).get("patch", 14)
    
    # Get ground truth patch indices (already in patch space)
    objects = annotation.get("objects", [])
    subject_id = qa_pair.get("subject_id")
    object_id = qa_pair.get("object_id")
    
    gt_subject_patch_indices = None
    gt_object_patch_indices = None
    
    for obj in objects:
        if obj.get("id") == subject_id and "patch_indices" in obj:
            gt_subject_patch_indices = obj["patch_indices"]
        if obj.get("id") == object_id and "patch_indices" in obj:
            gt_object_patch_indices = obj["patch_indices"]
    
    if gt_subject_patch_indices is None or len(gt_subject_patch_indices) == 0:
        raise ValueError(f"Subject patch_indices not found for subject_id={subject_id}")
    if gt_object_patch_indices is None or len(gt_object_patch_indices) == 0:
        raise ValueError(f"Object patch_indices not found for object_id={object_id}")
    
    # Create 2D binary masks for subject and object in grid space
    gt_subject_mask = np.zeros((grid_dim, grid_dim))
    gt_object_mask = np.zeros((grid_dim, grid_dim))
    
    for idx in gt_subject_patch_indices:
        row = idx // grid_dim
        col = idx % grid_dim
        if 0 <= row < grid_dim and 0 <= col < grid_dim:
            gt_subject_mask[row, col] = 1
    
    for idx in gt_object_patch_indices:
        row = idx // grid_dim
        col = idx % grid_dim
        if 0 <= row < grid_dim and 0 <= col < grid_dim:
            gt_object_mask[row, col] = 1
    
    # Calculate center of mass for ground truth masks (same method as attention)
    rows, cols = np.meshgrid(np.arange(grid_dim), np.arange(grid_dim), indexing='ij')
    gt_subject_sum = gt_subject_mask.sum()
    gt_object_sum = gt_object_mask.sum()
    
    if gt_subject_sum > 0:
        gt_subject_com_row = (gt_subject_mask * rows).sum() / gt_subject_sum
        gt_subject_com_col = (gt_subject_mask * cols).sum() / gt_subject_sum
        gt_subject_grid = (gt_subject_com_row, gt_subject_com_col)
    else:
        raise ValueError(f"Subject mask is empty for subject_id={subject_id}")
    
    if gt_object_sum > 0:
        gt_object_com_row = (gt_object_mask * rows).sum() / gt_object_sum
        gt_object_com_col = (gt_object_mask * cols).sum() / gt_object_sum
        gt_object_grid = (gt_object_com_row, gt_object_com_col)
    else:
        raise ValueError(f"Object mask is empty for object_id={object_id}")
    
    results = {}
    
    for layer_idx in specific_layers:
        if layer_idx >= len(input_step_attentions):
            continue
        
        # Get attention for this layer: [1, heads, seq, seq]
        layer_attn = input_step_attentions[layer_idx]
        layer_attn = layer_attn[0]  # Remove batch dim: [heads, seq, seq]
        
        num_heads = layer_attn.shape[0]
        results[layer_idx] = {}
        
        for head_idx in range(num_heads):
            # Get attention from source token to all tokens: [seq]
            head_attn = layer_attn[head_idx, source_token_idx, :]
            
            # Extract attention to image patches only: [num_image_tokens]
            image_attn = head_attn[image_token_positions]
            
            # Normalize to get probability distribution
            image_attn_sum = image_attn.sum()
            if image_attn_sum > 0:
                image_attn_probs = image_attn / image_attn_sum
            else:
                image_attn_probs = image_attn
            
            # Reshape to 2D grid: [grid_dim, grid_dim]
            if len(image_token_positions) != grid_dim * grid_dim:
                # If mismatch, we need to map properly
                attn_2d = np.zeros((grid_dim, grid_dim))
                for i, pos in enumerate(image_token_positions):
                    if i < grid_dim * grid_dim:
                        row = i // grid_dim
                        col = i % grid_dim
                        attn_2d[row, col] = image_attn_probs[i].item()
            else:
                attn_2d = image_attn_probs.reshape(grid_dim, grid_dim).cpu().numpy()
            
            # Calculate center of mass in grid coordinates
            rows, cols = np.meshgrid(np.arange(grid_dim), np.arange(grid_dim), indexing='ij')
            com_row = (attn_2d * rows).sum() / (attn_2d.sum() + 1e-9)
            com_col = (attn_2d * cols).sum() / (attn_2d.sum() + 1e-9)
            com_grid = (com_row, com_col)
            
            # Calculate distance to subject ground truth center of mass
            dist_to_subject = np.sqrt(
                (com_row - gt_subject_grid[0])**2 + 
                (com_col - gt_subject_grid[1])**2
            )
            
            # Calculate distance to object ground truth center of mass
            dist_to_object = np.sqrt(
                (com_row - gt_object_grid[0])**2 + 
                (com_col - gt_object_grid[1])**2
            )
            
            # Debug: print first result to verify
            # if layer_idx == specific_layers[0] and head_idx == 0:
            #     print(f"DEBUG - Source: {source_token_name}, Subject ID: {subject_id}, Object ID: {object_id}")
            #     print(f"DEBUG - GT Subject Grid: {gt_subject_grid}, GT Object Grid: {gt_object_grid}")
            #     print(f"DEBUG - Attention CoM: {com_grid}")
            #     print(f"DEBUG - Distance to Subject: {dist_to_subject}, Distance to Object: {dist_to_object}")
            
            results[layer_idx][head_idx] = {
                "com_grid": (float(com_row), float(com_col)),
                "gt_subject_grid": gt_subject_grid,
                "gt_object_grid": gt_object_grid,
                "distance_to_subject": float(dist_to_subject),
                "distance_to_object": float(dist_to_object),
                "attention_sum": float(image_attn_sum.item()),
                "source_token_type": source_token_name,
                "source_token_idx": int(source_token_idx),
            }
    
    return results

def plot_com_heatmaps_from_json(json_path, output_dir=None):
    """
    Load CoM results from JSON file and plot heatmaps.
    
    Args:
        json_path: Path to the head_com_results.json file
        output_dir: Directory to save plots (default: same directory as JSON file)
    """
    # Load JSON file
    with open(json_path, 'r') as f:
        com_results = json.load(f)
    
    if not com_results:
        print(f"No data found in {json_path}")
        return
    
    # Extract level from file path (e.g., "level_2/com_results_.../head_com_results.json")
    json_dir = os.path.dirname(json_path)
    json_basename = os.path.basename(json_dir)
    
    # Try to extract level from path
    level = None
    for part in json_path.split(os.sep):
        if part.startswith('level_'):
            try:
                level = int(part.split('_')[1])
                break
            except (ValueError, IndexError):
                continue
    
    if level is None:
        # Fallback: try to extract from directory name
        if 'level_' in json_basename:
            try:
                level = int(json_basename.split('level_')[1].split('_')[0])
            except (ValueError, IndexError):
                pass
    
    if level is None:
        print("Warning: Could not extract level from path. Using level 1 as default.")
        level = 1
    
    # Extract source_token_type from first entry
    source_token_type = com_results[0].get("source_token_type", "object")
    
    # Determine output directory
    if output_dir is None:
        output_dir = json_dir
    
    # Plot heatmaps
    plot_com_heatmaps(com_results, output_dir, level, source_token_type)
    print(f"Heatmaps saved to: {os.path.abspath(output_dir)}")

def plot_com_heatmaps(com_results, output_dir, level, source_token_type):
    """
    Plot heatmaps showing distance to subject/object for each head in each layer.
    
    Args:
        com_results: List of dicts with 'com_results' containing per-layer, per-head data
        output_dir: Directory to save the plots
        level: Data level for title
        source_token_type: Source token type used for CoM calculation (from args)
    """
    if not com_results:
        print("No CoM results to plot")
        return
    
    # Aggregate distances across all image/QA pairs with per-image normalization
    # Structure: {layer: {head: {'dist_subject': [...], 'dist_object': [...]}}}
    aggregated = {}
    
    for result in com_results:
        com_data = result.get("com_results", {})
        
        # Collect all distances for this image to find min/max
        all_distances_subject = []
        all_distances_object = []
        
        for layer_str, heads in com_data.items():
            for head_str, head_data in heads.items():
                dist_subj = head_data.get('distance_to_subject', 0)
                dist_obj = head_data.get('distance_to_object', 0)
                if dist_subj > 0:  # Only include non-zero distances
                    all_distances_subject.append(dist_subj)
                if dist_obj > 0:
                    all_distances_object.append(dist_obj)
        
        # Calculate min/max for this image
        if all_distances_subject:
            min_subj = min(all_distances_subject)
            max_subj = max(all_distances_subject)
            range_subj = max_subj - min_subj if max_subj > min_subj else 1.0
        else:
            min_subj, max_subj, range_subj = 0, 1, 1
        
        if all_distances_object:
            min_obj = min(all_distances_object)
            max_obj = max(all_distances_object)
            range_obj = max_obj - min_obj if max_obj > min_obj else 1.0
        else:
            min_obj, max_obj, range_obj = 0, 1, 1
        
        # Normalize and aggregate distances for this image
        for layer_str, heads in com_data.items():
            layer = int(layer_str)
            if layer not in aggregated:
                aggregated[layer] = {head: {'dist_subject': [], 'dist_object': []} 
                                     for head in range(32)}
            
            for head_str, head_data in heads.items():
                head = int(head_str)
                if head < 32:
                    dist_subj = head_data.get('distance_to_subject', 0)
                    dist_obj = head_data.get('distance_to_object', 0)
                    
                    # Normalize per image: (d_i - min(d_i)) / (max(d_i) - min(d_i))
                    if dist_subj > 0:
                        normalized_subj = (dist_subj - min_subj) / range_subj
                        aggregated[layer][head]['dist_subject'].append(normalized_subj)
                    
                    if dist_obj > 0:
                        normalized_obj = (dist_obj - min_obj) / range_obj
                        aggregated[layer][head]['dist_object'].append(normalized_obj)
    
    if not aggregated:
        print("No aggregated data to plot")
        return
    
    # Get layers and sort them
    layers = sorted(aggregated.keys())
    num_layers = len(layers)
    num_heads = 32
    
    # Create arrays for heatmaps
    dist_subject_heatmap = np.zeros((num_layers, num_heads))
    dist_object_heatmap = np.zeros((num_layers, num_heads))
    
    for i, layer in enumerate(layers):
        for head in range(num_heads):
            if aggregated[layer][head]['dist_subject']:
                dist_subject_heatmap[i, head] = np.mean(aggregated[layer][head]['dist_subject'])
            if aggregated[layer][head]['dist_object']:
                dist_object_heatmap[i, head] = np.mean(aggregated[layer][head]['dist_object'])
    
    # Create figure with two subplots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))
    
    # Plot distance to subject heatmap
    im1 = ax1.imshow(dist_subject_heatmap, aspect='auto', cmap='YlOrRd', interpolation='nearest', vmin=0, vmax=1)
    ax1.set_xlabel('Attention Head', fontsize=12)
    ax1.set_ylabel('Layer', fontsize=12)
    ax1.set_title(f'Average Distance to Subject CoM\n(Level {level}, Source: {source_token_type})', fontsize=14)
    ax1.set_yticks(range(num_layers))
    ax1.set_yticklabels(layers)
    ax1.set_xticks(range(0, num_heads, 4))
    ax1.set_xticklabels(range(0, num_heads, 4))
    plt.colorbar(im1, ax=ax1, label='Normalized Distance (0-1, per-image)')
    
    # Plot distance to object heatmap
    im2 = ax2.imshow(dist_object_heatmap, aspect='auto', cmap='YlOrRd', interpolation='nearest', vmin=0, vmax=1)
    ax2.set_xlabel('Attention Head', fontsize=12)
    ax2.set_ylabel('Layer', fontsize=12)
    ax2.set_title(f'Average Distance to Object CoM\n(Level {level}, Source: {source_token_type})', fontsize=14)
    ax2.set_yticks(range(num_layers))
    ax2.set_yticklabels(layers)
    ax2.set_xticks(range(0, num_heads, 4))
    ax2.set_xticklabels(range(0, num_heads, 4))
    plt.colorbar(im2, ax=ax2, label='Normalized Distance (0-1, per-image)')
    
    plt.tight_layout()
    
    # Save plot
    save_path = os.path.join(output_dir, "com_distance_heatmaps.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"CoM heatmaps saved to: {save_path}")

def plot_head_accuracy(results, output_dir, level):
    """
    Plot head probing accuracy heatmap.
    
    Args:
        results: dict with 'head_scores' containing list of dicts with 'layer', 'head', 'accuracy', 'std'
        output_dir: directory to save the plot
        level: data level for title
    """
    head_scores = results.get("head_scores", [])
    if not head_scores:
        print("No head scores to plot")
        return
    
    # Organize data by layer and head
    layers = sorted(set(s["layer"] for s in head_scores))
    num_layers = len(layers)
    num_heads = 32
    
    # Create heatmap array
    accuracy_heatmap = np.zeros((num_layers, num_heads))
    
    for score in head_scores:
        layer_idx = layers.index(score["layer"])
        head_idx = score["head"]
        if head_idx < num_heads:
            accuracy_heatmap[layer_idx, head_idx] = score["accuracy"]
    
    # Create figure
    plt.figure(figsize=(14, 6))
    
    im = plt.imshow(accuracy_heatmap, aspect='auto', cmap='viridis', interpolation='nearest')
    plt.xlabel('Attention Head', fontsize=12)
    plt.ylabel('Layer', fontsize=12)
    plt.title(f'Head Probing Accuracy (Level {level})\n{results.get("num_examples", 0)} examples', fontsize=14)
    plt.yticks(range(num_layers), layers)
    plt.xticks(range(0, num_heads, 4), range(0, num_heads, 4))
    plt.colorbar(im, label='Cross-Validation Accuracy')
    
    plt.tight_layout()
    
    # Save plot
    save_path = os.path.join(output_dir, "head_probing_accuracy.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"Head probing plot saved to: {save_path}")

def plot_accuracy_vs_distance(head_probing_results_path, com_results_path, output_dir, level):
    """
    Plot head probing accuracy vs CoM distance to subject/object.
    
    Args:
        head_probing_results_path: Path to head_probing_results.json
        com_results_path: Path to head_com_results.json
        output_dir: Directory to save the plot
        level: Data level for title
    """
    # Load head probing results
    with open(head_probing_results_path, "r") as f:
        head_results = json.load(f)
    
    # Load CoM results
    with open(com_results_path, "r") as f:
        com_results = json.load(f)
    
    # Aggregate CoM distances per head (average across all examples)
    # Structure: {layer: {head: {'dist_subject': [...], 'dist_object': [...]}}}
    com_aggregated = {}
    
    for result in com_results:
        com_data = result.get("com_results", {})
        for layer_str, heads in com_data.items():
            layer = int(layer_str)
            if layer not in com_aggregated:
                com_aggregated[layer] = {head: {'dist_subject': [], 'dist_object': []} 
                                        for head in range(32)}
            
            for head_str, head_data in heads.items():
                head = int(head_str)
                if head < 32:
                    com_aggregated[layer][head]['dist_subject'].append(
                        head_data.get('distance_to_subject', 0)
                    )
                    com_aggregated[layer][head]['dist_object'].append(
                        head_data.get('distance_to_object', 0)
                    )
    
    # Match head probing accuracy with CoM distances
    accuracies = []
    dists_subject = []
    dists_object = []
    dists_avg = []
    layers = []
    heads = []
    
    for score in head_results.get("head_scores", []):
        layer = score["layer"]
        head = score["head"]
        accuracy = score["accuracy"]
        
        if layer in com_aggregated and head in com_aggregated[layer]:
            dist_subj_list = com_aggregated[layer][head]['dist_subject']
            dist_obj_list = com_aggregated[layer][head]['dist_object']
            
            if dist_subj_list and dist_obj_list:
                avg_dist_subject = np.mean(dist_subj_list)
                avg_dist_object = np.mean(dist_obj_list)
                avg_dist = (avg_dist_subject + avg_dist_object) / 2
                
                accuracies.append(accuracy)
                dists_subject.append(avg_dist_subject)
                dists_object.append(avg_dist_object)
                dists_avg.append(avg_dist)
                layers.append(layer)
                heads.append(head)
    
    if not accuracies:
        print("No matching data found between head probing and CoM results")
        return
    
    # Create figure with subplots
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    
    # Plot 1: Accuracy vs Distance to Subject
    axes[0].scatter(dists_subject, accuracies, alpha=0.6, s=50)
    axes[0].set_xlabel('Average Distance to Subject CoM (grid units)', fontsize=11)
    axes[0].set_ylabel('Head Probing Accuracy', fontsize=11)
    axes[0].set_title('Accuracy vs Distance to Subject', fontsize=12)
    axes[0].grid(True, alpha=0.3)
    axes[0].axhline(y=0.5, linestyle="--", alpha=0.5, color='red', label='Random (0.5)')
    axes[0].legend()
    
    # Add correlation coefficient
    if len(dists_subject) > 1:
        corr_subj = np.corrcoef(dists_subject, accuracies)[0, 1]
        axes[0].text(0.05, 0.95, f'r = {corr_subj:.3f}', transform=axes[0].transAxes,
                    verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # Plot 2: Accuracy vs Distance to Object
    axes[1].scatter(dists_object, accuracies, alpha=0.6, s=50, color='orange')
    axes[1].set_xlabel('Average Distance to Object CoM (grid units)', fontsize=11)
    axes[1].set_ylabel('Head Probing Accuracy', fontsize=11)
    axes[1].set_title('Accuracy vs Distance to Object', fontsize=12)
    axes[1].grid(True, alpha=0.3)
    axes[1].axhline(y=0.5, linestyle="--", alpha=0.5, color='red', label='Random (0.5)')
    axes[1].legend()
    
    # Add correlation coefficient
    if len(dists_object) > 1:
        corr_obj = np.corrcoef(dists_object, accuracies)[0, 1]
        axes[1].text(0.05, 0.95, f'r = {corr_obj:.3f}', transform=axes[1].transAxes,
                    verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    # Plot 3: Accuracy vs Average Distance (subject + object)
    axes[2].scatter(dists_avg, accuracies, alpha=0.6, s=50, color='green')
    axes[2].set_xlabel('Average Distance to Subject+Object CoM (grid units)', fontsize=11)
    axes[2].set_ylabel('Head Probing Accuracy', fontsize=11)
    axes[2].set_title('Accuracy vs Average Distance', fontsize=12)
    axes[2].grid(True, alpha=0.3)
    axes[2].axhline(y=0.5, linestyle="--", alpha=0.5, color='red', label='Random (0.5)')
    axes[2].legend()
    
    # Add correlation coefficient
    if len(dists_avg) > 1:
        corr_avg = np.corrcoef(dists_avg, accuracies)[0, 1]
        axes[2].text(0.05, 0.95, f'r = {corr_avg:.3f}', transform=axes[2].transAxes,
                    verticalalignment='top', bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.5))
    
    plt.suptitle(f'Head Probing Accuracy vs CoM Distance (Level {level})', fontsize=14, y=1.02)
    plt.tight_layout()
    
    # Save plot
    save_path = os.path.join(output_dir, "accuracy_vs_distance.png")
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    plt.close()
    
    print(f"Accuracy vs distance plot saved to: {save_path}")

def plot_layer_accuracy(results, output_dir, level):
    """
    Plot layer accuracy and save to vis_results folder.

    Args:
        results: dict with 'layer_scores' containing list of dicts with 'layer', 'accuracy', 'std'
        output_dir: directory to save the plot
        level: data level for title
    """
    layer_scores = results.get("layer_scores", [])
    if not layer_scores:
        print("No layer scores to plot")
        return

    # Extract data
    layers = [s["layer"] for s in layer_scores]
    accuracies = [s["accuracy"] for s in layer_scores]
    num_examples = results.get("num_examples", 0)

    # Create figure
    plt.figure(figsize=(12, 6))

    # Plot line without error bars
    plt.plot(
        layers,
        accuracies,
        "o-",
        linewidth=2,
        markersize=8,
        label="Layer Accuracy",
    )

    # Add horizontal line at 0.5 (random chance)
    plt.axhline(y=0.5, linestyle="--", alpha=0.5, label="Random (0.5)")

    # Find and highlight best layer
    best_layer_idx = np.argmax(accuracies)
    best_layer = layers[best_layer_idx]
    best_acc = accuracies[best_layer_idx]
    plt.plot(
        best_layer,
        best_acc,
        "*",
        markersize=20,
        label=f"Best Layer {best_layer} ({best_acc:.3f})",
    )

    # Formatting
    plt.xlabel("Layer Index", fontsize=12)
    plt.ylabel("Cross-Validation Accuracy", fontsize=12)
    plt.title(
        f"Layer Probing Accuracy (Level {level})\n{num_examples} examples, {len(layers)} layers",
        fontsize=14,
    )
    plt.grid(True, alpha=0.3)
    plt.legend(loc="best")
    plt.xlim(-0.5, max(layers) + 0.5)
    plt.ylim(0, 1.0)
    plt.tight_layout()

    # Save plot
    os.makedirs(output_dir, exist_ok=True)
    plot_path = os.path.join(output_dir, "layer_probing_accuracy.png")
    plt.savefig(plot_path, dpi=150, bbox_inches="tight")
    plt.close()

    print(f"Plot saved to: {plot_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Probe model layers for yes/no decision encoding"
    )
    parser.add_argument(
        "--level", type=int, default=1, help="Data level to probe (0-4)"
    )
    parser.add_argument(
        "--max_images",
        type=int,
        default=None,
        help="Maximum number of images to process",
    )
    # parser.add_argument(
    #     "--output",
    #     type=str,
    #     default="layer_probing_results.json",
    #     help="Output JSON file",
    # )
    parser.add_argument(
        "--cv_folds", type=int, default=5, help="Number of CV folds"
    )
    parser.add_argument("--first_gen_token", action="store_true")
    parser.add_argument("--calc_com", action="store_true", 
                       help="Calculate center of mass for attention heads")
    parser.add_argument("--com_layers", type=int, nargs="+", 
                       default=None,
                       help="Layers to analyze for CoM (default: all layers)")
    parser.add_argument("--com_source_token", type=str, default="object",
                       choices=["subject", "relation", "object"],
                       help="Source token type for CoM calculation (default: object)")
    parser.add_argument("--plot_json", type=str, default=None,
                       help="Plot heatmaps from existing JSON file (path to head_com_results.json)")
    parser.add_argument("--skip_probing", action="store_true",
                       help="Skip layer probing and only run CoM calculation")
    parser.add_argument("--probe_heads", action="store_true",
                       help="Probe individual attention heads (requires attentions)")
    parser.add_argument("--head_layers", type=int, nargs="+", 
                       default=[13, 16, 19, 24],
                       help="Layers to probe for head probing (default: 13 16 19 24)")
    parser.add_argument("--skip_layer_probing", action="store_true",
                       help="Skip layer probing and only run head probing")
    args = parser.parse_args()

    # If --plot_json is provided, just plot and exit
    if args.plot_json:
        plot_com_heatmaps_from_json(args.plot_json)
        return

    # If only head probing is requested, skip layer probing
    if args.probe_heads and args.skip_layer_probing:
        print(f"Loading {MODEL_ID} for head probing only...")
        processor, model, device = _init_model(
            MODEL_ID,
            output_hidden_states=False,
            output_attentions=True,  # Need attentions for head probing
        )
        
        # Collect head probing data
        head_features_by_layer_head, labels, metadata = collect_head_probing_data(
            model, processor, args.level,
            max_images=args.max_images,
            specific_layers=args.head_layers,
            first_token=args.first_gen_token
        )
        
        if len(labels) == 0:
            print("No data collected. Exiting.")
            return
        
        print(f"\nProbing heads in layers {args.head_layers} on {len(labels)} examples...")
        
        # Probe each head in each layer
        results = {
            "level": args.level,
            "num_examples": len(labels),
            "layers": args.head_layers,
            "head_scores": [],
        }
        
        total_heads = sum(len(heads) for heads in head_features_by_layer_head.values())
        with tqdm(total=total_heads, desc="Probing heads") as pbar:
            for layer_idx in sorted(head_features_by_layer_head.keys()):
                heads = head_features_by_layer_head[layer_idx]
                for head_idx in sorted(heads.keys()):
                    head_features = heads[head_idx]
                    if len(head_features) != len(labels):
                        pbar.update(1)
                        continue
                    
                    mean_acc, std_acc = probe_head(head_features, labels, cv_folds=args.cv_folds)
                    
                    results["head_scores"].append({
                        "layer": layer_idx,
                        "head": head_idx,
                        "accuracy": float(mean_acc),
                        "std": float(std_acc),
                    })
                    pbar.update(1)
        
        # Save results
        timestamp = time.strftime("%Y%m%d-%H%M%S")
        base_output_dir = "vis_results"
        level_output = os.path.join(base_output_dir, f"level_{args.level}")
        token_suffix = "_first_token" if args.first_gen_token else ""
        head_output = os.path.join(level_output, f"head_probing{token_suffix}_{timestamp}")
        os.makedirs(head_output, exist_ok=True)
        
        # Plot and save
        plot_head_accuracy(results, head_output, args.level)
        
        # Save JSON results
        results_path = os.path.join(head_output, "head_probing_results.json")
        with open(results_path, "w") as f:
            json.dump(results, f, indent=2)
        
        print(f"\nHead probing results saved to: {os.path.abspath(head_output)}")
        
        # Check if CoM results exist and create comparison plot
        # Look for most recent com_results directory
        com_dirs = [d for d in os.listdir(level_output) if d.startswith("com_results_")]
        if com_dirs:
            # Use most recent CoM results
            latest_com_dir = sorted(com_dirs)[-1]
            com_results_path = os.path.join(level_output, latest_com_dir, "head_com_results.json")
            if os.path.exists(com_results_path):
                print(f"\nCreating accuracy vs distance comparison plot...")
                plot_accuracy_vs_distance(results_path, com_results_path, head_output, args.level)
        
        return  # Exit early, skip layer probing
    
    # If only CoM is requested, skip probing entirely
    if args.calc_com and args.skip_probing:
        print(f"Loading {MODEL_ID} for CoM calculation only...")
        processor, model, device = _init_model(
            MODEL_ID,
            output_hidden_states=True,
            output_attentions=True,  # Need attentions for CoM
        )
        
        com_results = collect_head_com_data(
            model, processor, args.level, 
            max_images=args.max_images,
            specific_layers=args.com_layers,
            source_token_type=args.com_source_token
        )
        
        # Save CoM results
        timestamp = time.strftime("%Y%m%d-%H%M%S")
        base_output_dir = "vis_results"
        level_output = os.path.join(base_output_dir, f"level_{args.level}")
        com_output = os.path.join(level_output, f"com_results_{timestamp}")
        os.makedirs(com_output, exist_ok=True)
        
        com_output_path = os.path.join(com_output, "head_com_results.json")
        with open(com_output_path, "w") as f:
            json.dump(com_results, f, indent=2)
        
        # Plot heatmaps
        plot_com_heatmaps(com_results, com_output, args.level, source_token_type=args.com_source_token)
        
        print(f"CoM results saved to: {os.path.abspath(com_output_path)}")
        
        # Check if head probing results exist and create comparison plot
        head_dirs = [d for d in os.listdir(level_output) if d.startswith("head_probing")]
        if head_dirs:
            latest_head_dir = sorted(head_dirs)[-1]
            head_results_path = os.path.join(level_output, latest_head_dir, "head_probing_results.json")
            if os.path.exists(head_results_path):
                print(f"\nCreating accuracy vs distance comparison plot...")
                plot_accuracy_vs_distance(head_results_path, com_output_path, com_output, args.level)
        
        return  # Exit early, skip all probing

    print(f"Loading {MODEL_ID}...")
    processor, model, device = _init_model(
        MODEL_ID,
        output_hidden_states=True,
        output_attentions=False,
    )

    num_layers = len(model.language_model.layers)
    print(f"Model has {num_layers} layers")

    # Collect data
    hidden_states_by_layer, labels, metadata = collect_probing_data(
        model, processor, args.level, max_images=args.max_images, first_token=args.first_gen_token
    )

    if len(labels) == 0:
        print("No data collected. Exiting.")
        return

    print(f"\nProbing {num_layers} layers on {len(labels)} examples...")

    # Probe each layer
    results = {
        "level": args.level,
        "num_examples": len(labels),
        "num_layers": num_layers,
        "layer_scores": [],
    }

    for layer_idx in tqdm(range(num_layers), desc="Probing layers"):
        if layer_idx not in hidden_states_by_layer:
            continue

        hidden_states = hidden_states_by_layer[layer_idx]
        if len(hidden_states) != len(labels):
            print(
                f"Warning: Layer {layer_idx} has {len(hidden_states)} states "
                f"but {len(labels)} labels"
            )
            continue

        mean_acc, std_acc = probe_layer(
            hidden_states, labels, cv_folds=args.cv_folds
        )

        results["layer_scores"].append(
            {
                "layer": layer_idx,
                "accuracy": float(mean_acc),
                "std": float(std_acc),
            }
        )

        print(f"Layer {layer_idx:2d}: {mean_acc:.4f} ± {std_acc:.4f}")

    # # Save results
    # with open(args.output, "w") as f:
    #     json.dump(results, f, indent=2)

    # print(f"\nResults saved to {args.output}")
    best_layer_info = max(
        results["layer_scores"], key=lambda x: x["accuracy"]
    )
    print(f"\nBest layer: {best_layer_info}")

    # Create vis_results output directory and plot
    timestamp = time.strftime("%Y%m%d-%H%M%S")
    base_output_dir = "vis_results"
    level_output = os.path.join(base_output_dir, f"level_{args.level}")
    # Include suffix if using first generated token
    token_suffix = "_first_token" if args.first_gen_token else ""
    probing_output = os.path.join(level_output, f"probing{token_suffix}_{timestamp}")
    os.makedirs(probing_output, exist_ok=True)

    # Plot and save
    plot_layer_accuracy(results, probing_output, args.level)

    # Also save a copy of the results JSON in the vis_results folder
    results_copy_path = os.path.join(
        probing_output, "layer_probing_results.json"
    )
    with open(results_copy_path, "w") as f:
        json.dump(results, f, indent=2)

    print(f"\nVisualization results saved to: {os.path.abspath(probing_output)}")
    
    # Optionally probe heads
    if args.probe_heads:
        print(f"\nProbing attention heads...")
        # Need to reinitialize model with attentions enabled for head probing
        processor_heads, model_heads, device_heads = _init_model(
            MODEL_ID,
            output_hidden_states=False,
            output_attentions=True,  # Need attentions for head probing
        )
        
        # Collect head probing data
        head_features_by_layer_head, head_labels, head_metadata = collect_head_probing_data(
            model_heads, processor_heads, args.level,
            max_images=args.max_images,
            specific_layers=args.head_layers,
            first_token=args.first_gen_token
        )
        
        if len(head_labels) > 0:
            print(f"\nProbing heads in layers {args.head_layers} on {len(head_labels)} examples...")
            
            # Probe each head in each layer
            head_results = {
                "level": args.level,
                "num_examples": len(head_labels),
                "layers": args.head_layers,
                "head_scores": [],
            }
            
            total_heads = sum(len(heads) for heads in head_features_by_layer_head.values())
            for layer_idx in sorted(head_features_by_layer_head.keys()):
                heads = head_features_by_layer_head[layer_idx]
                for head_idx in sorted(heads.keys()):
                    head_features = heads[head_idx]
                    if len(head_features) != len(head_labels):
                        continue
                    
                    mean_acc, std_acc = probe_head(head_features, head_labels, cv_folds=args.cv_folds)
                    
                    head_results["head_scores"].append({
                        "layer": layer_idx,
                        "head": head_idx,
                        "accuracy": float(mean_acc),
                        "std": float(std_acc),
                    })
            
            # Save head probing results in same directory
            plot_head_accuracy(head_results, probing_output, args.level)
            
            head_results_path = os.path.join(probing_output, "head_probing_results.json")
            with open(head_results_path, "w") as f:
                json.dump(head_results, f, indent=2)
            
            print(f"Head probing results saved to: {os.path.abspath(head_results_path)}")
            
            # If CoM results exist, create comparison plot
            com_output = os.path.join(level_output, f"com_results_{timestamp}")
            com_results_path = os.path.join(com_output, "head_com_results.json")
            if os.path.exists(com_results_path):
                print(f"\nCreating accuracy vs distance comparison plot...")
                plot_accuracy_vs_distance(head_results_path, com_results_path, probing_output, args.level)
    
    # Optionally calculate CoM for attention heads
    if args.calc_com:
        print(f"\nCalculating center of mass for attention heads...")
        # Need to reinitialize model with attentions enabled for CoM calculation
        processor_com, model_com, device_com = _init_model(
            MODEL_ID,
            output_hidden_states=True,
            output_attentions=True,  # Need attentions for CoM
        )
        
        com_results = collect_head_com_data(
            model_com, processor_com, args.level, 
            max_images=args.max_images,
            specific_layers=args.com_layers,
            source_token_type=args.com_source_token
        )
        
        # Save CoM results
        com_output = os.path.join(level_output, f"com_results_{timestamp}")
        os.makedirs(com_output, exist_ok=True)
        
        com_output_path = os.path.join(com_output, "head_com_results.json")
        with open(com_output_path, "w") as f:
            json.dump(com_results, f, indent=2)
        
        # Plot heatmaps
        plot_com_heatmaps(com_results, com_output, args.level, source_token_type=args.com_source_token)
        
        print(f"CoM results saved to: {os.path.abspath(com_output_path)}")
        
        # Check if head probing results exist and create comparison plot
        head_dirs = [d for d in os.listdir(level_output) if d.startswith("head_probing")]
        if head_dirs:
            latest_head_dir = sorted(head_dirs)[-1]
            head_results_path = os.path.join(level_output, latest_head_dir, "head_probing_results.json")
            if os.path.exists(head_results_path):
                print(f"\nCreating accuracy vs distance comparison plot...")
                plot_accuracy_vs_distance(head_results_path, com_output_path, com_output, args.level)


if __name__ == "__main__":
    main()