level: 4
id: "00010_b"

num_questions: 15

# Attention source: first_generated_token, rel_phrase
attention_source: first_generated_token
# Attention detail level: simple, detailed
attention_mode: simple

# Optional overrides
model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
base_data_path: "/home/kkarthikeyan/deep-learning/DeepLearningProject/Synthetic-Data/vlm_levels"
base_output_dir: "vis_results"